version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    env_file:
      - .env
    environment:
      - MODEL_NAME=${MODEL_NAME}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./data/models:/app/models
    command: ["bash", "-c", "sh /docker/pull_model.sh && ollama serve"] 

networks:
  default:
    driver: bridge

volumes:
  models: